### ISSUE TITLE
Acesso a aplicação

### ISSUE THREAD

**Issue by b-sep** [TreinaDev/pagamentos-td08-time01#1]
Eu usuário administrador faço login e logout na aplicação com email de dominio @usuerubis.com.br.

**Comment by Jhonny4975** [comment]
**Implementações:**
- Adicionado gem [devise](https://github.com/heartcombo/devise);
- Devise configurado;
- Novo modelo de admin com os atributos full_name, cpf, email e password;
- Implementação de testes de UI;
- Validações de presença e dominio;
- Permitido o registro de dados nos atributos adicionais;
- Configuração do I18n.
